
Vagrant.configure(2) do |config|
  
  config.vm.box = "debian8"
  config.ssh.insert_key = false
  config.vm.network "forwarded_port", guest: 81, host: 8081
  config.vm.network "forwarded_port", guest: 1338, host: 1338
  config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc' ]

    config.vm.provider "virtualbox" do |vb|
    vb.memory = "16384"
    vb.cpus = "4"
  end

end
